[package]
name = "bntx"
version = "0.1.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>", "ScanMountGoat <>"]
edition = "2018"

[dependencies]
binrw = "0.14.1"
image_dds = "0.6.2"
tegra_swizzle = "0.4.0"
thiserror = "1.0"
xc3_write = "0.15.0"