[package]
name = "bntx"
version = "0.1.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>", "ScanMountGoat <>"]
edition = "2018"

[dependencies]
binrw = "0.13.3"
image_dds = "0.5.1"
tegra_swizzle = "0.3.1"
thiserror = "1.0"
xc3_write = "0.9.0"
